version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lpr_postgres
    restart: always
    environment:
      POSTGRES_USER: lpruser
      POSTGRES_PASSWORD: lprpass
      POSTGRES_DB: lprdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: