"""Identify_car

Revision ID: b5c73cedb960
Revises: 18d5dfc2b695
Create Date: 2025-05-26 10:40:18.898027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c73cedb960'
down_revision = '18d5dfc2b695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identify_car', schema=None) as batch_op:
        batch_op.alter_column('extra_info',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identify_car', schema=None) as batch_op:
        batch_op.alter_column('extra_info',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
